add Chris' population code and do a basic test

In [1]:
import sys
import os

sys.path.append('./src')

from team_malthus import pop

# get the scalar population
test_pop = pop.population( 
        year=2020, 
        sex="m",
        age_range="13-24",
        place="NAM") 

print(test_pop)

# get a dataframe with bucketed stats for a country
test_df = pop.population_df(["USA", "NAM"])
display(test_df)

284120

                      male_0_4  female_0_4    male_5_9  female_5_9  \
country       date
Namibia       2022    166945.0    166301.0    157787.0    158902.0
              2021    166521.0    166054.0    155285.0    156738.0
              2020    165958.0    165650.0    152328.0    154033.0
              2019    165349.0    165170.0    149064.0    150923.0
              2018    164604.0    164513.0    145544.0    147456.0
...                        ...         ...         ...         ...
United States 1964  10238054.0   9892122.0  10229317.0   9868928.0
              1963  10326196.0   9984933.0  10102636.0   9747508.0
              1962  10374649.0  10035091.0   9913431.0   9568514.0
              1961  10370108.0  10029071.0   9880207.0   9515106.0
              1960  10294500.0   9951249.0   9698745.0   9346706.0

                    male_10_14  female_10_14  male_15_19  female_15_19  \
country       date
Namibia       2022    138796.0      141572.0    118803.0      122027.0
              2021    134288.0      137180.0    117406.0      120602.0
              2020    130102.0      133073.0    116947.0      120093.0
              2019    126393.0      129433.0    117391.0      120493.0
              2018    123276.0      126387.0    118329.0      121407.0
...                        ...           ...         ...           ...
United States 1964   9361755.0     9014905.0   8052724.0     7951304.0
              1963   9027461.0     8671299.0   7805866.0     7748472.0
              1962   8888062.0     8574165.0   7456087.0     7371659.0
              1961   8627853.0     8360051.0   6940722.0     6878559.0
              1960   8334413.0     8048264.0   6582483.0     6548531.0

                    male_20_24  female_20_24  ...  male_60_64  female_60_64  \
country       date                            ...
Namibia       2022    115272.0      118436.0  ...     23387.0       32366.0
              2021    115308.0      118434.0  ...     22971.0       31661.0
              2020    115136.0      118321.0  ...     22407.0       30845.0
              2019    115394.0      118705.0  ...     21701.0       29931.0
              2018    116388.0      119830.0  ...     20982.0       29001.0
...                        ...           ...  ...         ...           ...
United States 1964   6268166.0     6593502.0  ...   3478614.0     3889258.0
              1963   6007957.0     6309660.0  ...   3497785.0     3895651.0
              1962   5699131.0     5984578.0  ...   3495944.0     3881892.0
              1961   5575583.0     5770351.0  ...   3458132.0     3834536.0
              1960   5480961.0     5626027.0  ...   3466668.0     3833465.0

                    male_65_69  female_65_69  male_70_74  female_70_74  \
country       date
Namibia       2022     16275.0       24924.0     10542.0       17780.0
              2021     16274.0       24653.0     10690.0       17456.0
              2020     16089.0       24203.0     10666.0       16950.0
              2019     15706.0       23580.0     10450.0       16268.0
              2018     15270.0       22848.0     10188.0       15606.0
...                        ...           ...         ...           ...
United States 1964   3024239.0     3645486.0   2283075.0     2859831.0
              1963   2982959.0     3556866.0   2278105.0     2803929.0
              1962   2918741.0     3433035.0   2283351.0     2762829.0
              1961   2891410.0     3349577.0   2259822.0     2691523.0
              1960   2870722.0     3280254.0   2213496.0     2600301.0

                    male_75_79  female_75_79  male_80_UP  female_80_UP
country       date
Namibia       2022      6202.0       11255.0      4109.0       10796.0
              2021      6286.0       11088.0      4366.0       11105.0
              2020      6193.0       10733.0      4463.0       11080.0
              2019      5945.0       10229.0      4373.0       10726.0
              2018      5679.0        9734.0      4249.0       10359.0
...                        ...           ...         ...           ...
United States 1964   1487650.0     1961767.0   1160164.0     1842892.0
              1963   1464525.0     1901340.0   1128657.0     1769622.0
              1962   1440973.0     1843506.0   1101736.0     1705335.0
              1961   1413009.0     1783765.0   1072528.0     1640941.0
              1960   1377026.0     1718929.0   1041819.0     1574181.0

[126 rows x 34 columns]